version: '3'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    image: ql-events/wordpress:${WORDPRESS_IMAGE_VERSION:-latest}
    build:
      context: .
    depends_on:
      - mysql
      - mysql_phpunit
    ports:
      - "8080:80"
    volumes:
      - ./local/public:/var/www/html # WP core files.
      - .:/var/www/html/wp-content/plugins/ql-events
      - ./codeception.dist.yml:/var/www/html/wp-content/plugins/ql-events/codeception.yml
      - ./local/.htaccess:/var/www/html/.htaccess
    environment:
      WP_ROOT_FOLDER: /var/www/html
      COMPOSER_HOME: /tmp/.composer
      APACHE_RUN_USER: "#1000" # Ensure Apache can write to the filesystem.

  mysql_phpunit:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
