name: Package for Release

on:
  release:
    types: [ published ]

jobs:
  tag:
    name: Package new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, intl
          tools: composer
      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
      - name: Create Artifact
        run: |
          mkdir plugin-build
          composer archive -vvv --format=zip --file="plugin-build/ql-events"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ql-events
          path: plugin-build/ql-events.zip
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: plugin-build/ql-events.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
